"""add warnings

Revision ID: c67e567852a2
Revises: 5c3ba044dc64
Create Date: 2023-10-17 06:01:16.450387

"""

# revision identifiers, used by Alembic.
revision = 'c67e567852a2'
down_revision = '5c3ba044dc64'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('datasource', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_file_warnings', sa.BigInteger(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('datasource', schema=None) as batch_op:
        batch_op.drop_column('total_file_warnings')

    # ### end Alembic commands ###
